version: '3.7'

services:
  tb:
    depends_on:
      - postgres
    build:
      context: .
    environment:
      BOT_NAME: $BOT_NAME
      BOT_TOKEN: $BOT_TOKEN
      BOT_DB_USERNAME: $BOT_DB_USERNAME
      BOT_DB_PASSWORD: $BOT_DB_PASSWORD
      BOT_URL: $BOT_URL
    restart: always

  postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
