version: "3.7"
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: testPassword
      POSTGRES_USER: testName
      POSTGRES_DB: testDB
    ports:
      - 5434:5432





