version: '3.7'

services:
  tb:
    depends_on:
      - postgres
    build:
      context: .
    environment:
      BOT_NAME: $BOT_NAME
      BOT_TOKEN: $BOT_TOKEN
      BOT_DB_USERNAME: $BOT_DB_USERNAME
      BOT_DB_PASSWORD: $BOT_DB_PASSWORD
      BOT_URL: $BOT_URL
    restart: always

  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: Password
      POSTGRES_USER: Name
      POSTGRES_DB: tbDB
    ports:
      - 5433:5432
